### ISSUE TITLE
Anaconda gfortran problem

### ISSUE THREAD

**Issue by dthoma6** [rweigel/hxform#5]
I experienced a problem building hxform on a MacBook Pro (15-inch, 2017) running MacOS Monterey 12.4, the program failed to install with an error:

_...
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libm.tbd' for architecture x86_64
..._

An issue with the Anaconda virtual environment caused this problem.  I was compiling hxform as part of a magnetovis installation, which required python 3.8.8, but my MacBook had python 3.9.12.  So I set up a Anaconda virtual environment with conda's python 3.8.8 and conda's gfortran.  Attempting to install magnetovis and hxform led to the error message above.  

This problem is repeatable with other Fortran code.  To illustrate, I tried to compile a simple Fortran program, tmp.f, which contained:

      PROGRAM Triangle
      IMPLICIT NONE
      REAL :: a, b, c, Area
      PRINT *, 'Welcome, please enter the
     1         lengths of the 3 sides.'
      READ *, a, b, c
      PRINT *, 'Triangle''s area:  ', Area(a,b,c)
      END PROGRAM Triangle
      FUNCTION Area(x,y,z)
      IMPLICIT NONE
      REAL :: Area            ! function type
      REAL, INTENT( IN ) :: x, y, z
      REAL :: theta, height
      theta = ACOS((x**2+y**2-z**2)/(2.0*x*y))
      height = x*SIN(theta); Area = 0.5*y*height
      END FUNCTION Area

The command, gfortran tmp.f, gives a similar error message:

_ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libm.tbd' for architecture x86_64
collect2: error: ld returned 1 exit status_

To resolve the issue, I setup a new Anaconda virtual environment with python 3.8.8, but using the homebrew gfortran (in other words, I didn't install conda's gfortran).  In this new environment, tmp.f compiled and executed.  And magnetovis with hxform properly installed.

**Comment by rweigel** [comment]
The problem seems to be due to the fact that Anaconda's `gfortran` uses the OS-X 10.9 SDK: https://github.com/ContinuumIO/anaconda-issues/issues/9096 As a result, on OSX-11, the headers needed by `gfortran` are not found because they are not installed by default with X-Code.

The solution seems to be to use the brew version of `gfortran`.  So the steps required are

1. Install `homebrew` using the command at https://brew.sh/.
2. On the command line `brew install gfortran`
3. If you have installed `gfortran` using conda, execute `conda uninstall gfortran`
4. Test by creating `test.f` with the following content (keep indentation)

```fortran
      program main

      implicit none

      write ( *, '(a)' ) '  Hello, world!'

      stop
      end
```

and then try `gfortran test.f`.

5. If that works, you should be able to 

```
git clone https://github.com/rweigel/hxform
cd hxform;
pip install -e .
python hxform_demo.py
```
